name: encuestor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.0
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.4
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  uuid: ^4.5.2
  pdf: ^3.10.8
  printing: ^5.11.1
  open_file: ^3.3.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
